### ISSUE TITLE
Setting Spawn Undead horses to false doesnt work

### ISSUE THREAD

**Issue by Andyghandi** [NightKosh/Gravestone-mod-Extended#179]
Hi, I want to disable the horses added by this mod. They spawn in my mobs spawner from cursed earth and when they die, they leave a gravestone, which clogs up my spawner. I have disabled, CreateCorpsesForModdedNotVanillaHorses and SpawnUndeadHorses, in the configs, but horses still spawns and graves are still generated. 

Using forge 2770 and latest version of this mod

**Comment by Andyghandi** [comment]
Just to be clear, Undead horses spawn elsewhere in the world too, even though configs for them are set to false. However, I turned of the generate pet gravestones option, and this turned the undead horses gravestones off.

**Comment by NightKosh** [comment]
"SpawnUndeadHorses" option disable natural spawn of Skeleton and Zombie horses
but you should also disable spawn of skeleton and zombie raiders by "SpawnSkeletonRaidersInTheWorld" and "SpawnZombieRaidersInTheWorld", because those mobs spawn on undead horses.
As for "CreateCorpsesForModdedNotVanillaHorses" - this option prevents corps generation not graves.

Anyway my undead horses create grave on death only if it were tamed(which can't be done at the moment) - so the reason of this proble somewhere in "extra utilities 2" "cursed earth". I have no ideas how exactly it spawn mobs so can't help you with it. Ask its developer about it please.
